[workspace]
members = [
    "2/end_rust_modules",
    "2/start_rust_modules",
    "2/start_sqlx",
    "2/end_sqlx",
    "2/start_lazy_static",
    "2/end_lazy_static",
    "2/start_fake",
    "2/end_fake",
    "2/start_mockall",
    "2/end_mockall",
    "final/twitter-api"
]