version: "3.8"

services:
  server:
    image: chatterserver
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - db
    environment:
      ENV: development
      PORT: 4001
      HOST: "0.0.0.0"
      POSTGRES_HOST: "db"
      POSTGRES_PORT: 5432
      POSTGRES_PASSWORD: chatter
      POSTGRES_USER: chatter
      POSTGRES_DB: chatter
    ports:
      - "4001:4001"
  db:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: chatter
      POSTGRES_USER: chatter
      POSTGRES_DB: chatter
    volumes:
      - ./dbdata:/var/lib/postgresql/data
