version: "3.8"

services:
  pdb:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432
      POSTGRES_PASSWORD: chatter
      POSTGRES_USER: chatter
      POSTGRES_DB: chatter
    volumes:
      - ./dbdata:/var/lib/postgresql/data
